group.jupyter=Jupyter
jupyter.add.cell=Add cell
jupyter.cell.type=Change cell type
jupyter.compare.notebooks=Compare Jupyter notebooks
jupyter.preview.markdown.cell=Preview Markdown cell
jupyter.run.cell=Run Cell
